package com.nideas.api.userservice.data.dto.website;

import lombok.Data;

/** Created by Nanugonda on 7/10/2018. */
@Data
public class StateData {

  private long id;
  private String name;
  private long countryId;
  private String countryName;

  // Getters and Setters are generated by the class level annotation lombok.Data
}
