package com.nideas.api.userservice.data.dto.auth;

import javax.validation.constraints.NotBlank;
import lombok.Data;

/** Created by Nanugonda on 7/15/2018. */
@Data
public class SignUpRequest extends AbstractRequest {
  @NotBlank private String username;
  private String organization;
  @NotBlank private String firstName;
  private String middleName;
  @NotBlank private String lastName;
  @NotBlank private String password;
  @NotBlank private String email;
  private String phone;
  // Getters and Setters are generated by the class level annotation lombok.Data
}
