version: '3'
services:
  postgres-docker-container:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nideasdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - default


  nideas-api-user-service-app:
    image: nideas-api-user-service-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-docker-container
    ports:
      - 5050:5050
    networks:
      - default
