package com.nideas.api.userservice.data.dto.user;

import com.nideas.api.userservice.data.db.entity.client.Gender;
import lombok.Data;

/** Created by Nanugonda on 6/26/2018. */
@Data
public class ClientData extends User {

  private Gender gender;
  // Getters and Setters are generated by the class level annotation lombok.Data
}
