package com.nideas.api.userservice.data.dto.user;

import com.nideas.api.userservice.enumeration.UserRole;
import java.time.LocalDateTime;
import javax.validation.constraints.NotNull;
import lombok.Data;

/** Created by Nanugonda on 8/14/2018. */
@Data
public class User {

  private long id;
  private String username;
  private String password;
  private String userStatus;
  private String firstName;
  private String middleName;
  private String lastName;
  private String phone;
  private String email;
  private String addressLine1;
  private String addressLine2;
  private String addressLine3;
  private String city;
  private String state;
  private String country;
  private Integer zipCode;
  private String latitudeLongitude;
  private String token;
  private LocalDateTime expiry;

  @NotNull
  private UserRole userRole;

  // Getters and Setters are generated by the class level annotation lombok.Data
}
