package com.nideas.api.userservice.data.db.entity.location;

import com.nideas.api.userservice.data.db.entity.AuditEntity;
import lombok.Data;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/** Created by Nanugonda on 6/20/2018. */
@Data
@Entity
@Table(name = "state")
public class State extends AuditEntity {

  @Id
  @Column(name = "id")
  private Long id;

  @Column(name = "name")
  private String name;

  @JoinColumn(name = "country_id", referencedColumnName = "id")
  @ManyToOne(optional = false, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  private Country country;

  // Getters and Setters are generated by the class level annotation lombok.Data
}
