package com.nideas.api.userservice.data.db.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/** Created by Nanugonda on 6/19/2018. */
@Data
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(
    value = {"date_created", "date_modified"},
    allowGetters = true)
public abstract class AuditEntity implements Serializable {

  @Column(name = "date_created", nullable = false, updatable = false)
  @CreatedDate
  private LocalDateTime createdDate;

  @Column(name = "date_modified", nullable = false)
  @LastModifiedDate
  private LocalDateTime modifiedDate;

  // Getters and Setters are generated by the class level annotation lombok.Data
}
