package com.nideas.api.userservice.data.db.entity.provider;

import com.nideas.api.userservice.data.db.entity.AuditEntity;
import com.nideas.api.userservice.enumeration.UserStatus;
import java.time.LocalDateTime;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import lombok.Data;

/** Created by Nanugonda on 6/19/2018. */
@Data
@Entity
@Table(name = "provider")
public class Provider extends AuditEntity {

  @Id
  @Column(name = "id")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;

  @Column(name = "username")
  private String username;

  @Column(name = "password")
  private String password;

  @Enumerated(EnumType.STRING)
  @Column(name = "status")
  private UserStatus userStatus;

  @Column(name = "organization")
  private String organization;

  @Column(name = "first_name")
  @Size(max = 1000)
  private String firstName;

  @Column(name = "middle_name")
  private String middleName;

  @Column(name = "last_name")
  private String lastName;

  @Column(name = "phone")
  private String phone;

  @Column(name = "email")
  private String email;

  @Column(name = "address_line1")
  private String addressLine1;

  @Column(name = "address_line2")
  private String addressLine2;

  @Column(name = "address_line3")
  private String addressLine3;

  @Column(name = "city")
  private String city;

  @Column(name = "state")
  private String state;

  @Column(name = "country")
  private String country;

  @Column(name = "zipcode")
  private Integer zipCode;

  @Column(name = "description")
  private String description;

  @Column(name = "lat_long")
  private String latitudeLongitude;

  @Column(name = "token")
  private String token;

  @Column(name = "expiry")
  private LocalDateTime expiry;

  @ManyToMany(cascade = CascadeType.ALL)
  @JoinTable(
      name = "provider_facility",
      joinColumns = {@JoinColumn(name = "provider_id")},
      inverseJoinColumns = {@JoinColumn(name = "facility_id")})
  private Set<Facility> facilities;

  // Getters and Setters are generated by the class level annotation lombok.Data
}
